/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lmy_ffmpeg_FFmpegNative */

#ifndef _Included_com_lmy_ffmpeg_FFmpegNative
#define _Included_com_lmy_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lmy_ffmpeg_FFmpegNative
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lmy_ffmpeg_FFmpegNative_avcodec_1find_1decoder
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
